services:
    fallout.player.ability.factory:
        class: Fallout\GameBundle\Components\Player\Main\Special\AbilityFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    fallout.player.ability.manager:
        class: Fallout\GameBundle\Components\Player\Main\AbilitiesManager
        arguments: ['@fallout.player.ability.factory']
        calls:
            - ['createAbilities']

    fallout.player.main:
        class: Fallout\GameBundle\Components\Player\Main\MainPlayer
        arguments: ['@fallout.player.ability.manager', '@doctrine.orm.default_entity_manager']

    fallout.player.enemy.factory:
        class: Fallout\GameBundle\Components\Player\Enemy\EnemyFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    fallout.scenario.manager:
        class: Fallout\GameBundle\Components\Scenario\ScenarioManager
        arguments: ['@doctrine.orm.default_entity_manager', '@fallout.player.enemy.factory']