version: '2'

services:
    code:
        image: busybox
        command: /bin/true
        container_name: fallout_cli_code
        volumes:
            - ./code_link:/var/www
    db:
        build: ./db
        container_name: fallout_cli_db
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    php-fpm:
        build: ./php-fpm
        container_name: fallout_cli_php-fpm
        volumes_from:
            - code
        volumes:
            - ~/.composer:/root/.composer
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ./logs/fallout_cli:/var/log/fallout_cli
        links:
            - db
    nginx:
        build: ./nginx
        container_name: fallout_cli_nginx
        ports:
            - 81:80
        links:
            - php-fpm
        volumes_from:
            - code
        volumes:
            - ./logs/nginx:/var/log/nginx
    node-js:
        build: ./node
        container_name: fallout_cli_node-js
        volumes_from:
            - php-fpm
        depends_on:
            - php-fpm
